server:
  port: 8081
spring:
  application:
    name: hospital-users
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}/postgres?currentSchema=${SCHEMA}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/liquibaseConfig.yml
    liquibase-schema: ${SCHEMA}
  jackson:
    default-property-inclusion: NON_NULL
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
    topic: finance
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    prefer-ip-address: true