server:
  port: ${SERVER_PORT}
spring:
  application:
    name: hospital-users
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
  jackson:
    default-property-inclusion: NON_NULL
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      topic: finance
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    prefer-ip-address: true